#!/bin/bash
# Environment variables for adopted vault folder mapping
# Generated by /adopt — edit vault-config.json and re-run /adopt to update

export DAILY_NOTES_DIR="Daily"
export GOALS_DIR="Goals"
export PROJECTS_DIR="Projects"
export TEMPLATES_DIR="Templates"
export INBOX_DIR="Inbox"
export ARCHIVES_DIR="Archive"
export MEETINGS_DIR="Meetings"
export PEOPLE_DIR="People"
export REVIEWS_DIR="Reviews"
